config/routes.rb
Rails.application.routes.draw do
  get 'link_urls/new'
  get 'link_urls/show'
  get 'link_urls/url_lists'
  post 'link_urls/create'
  get 'link_urls/index'
  root to: 'link_urls#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link_url.rb
require 'uri'
class LinkUrl < ApplicationRecord
  #validates :original_url, :format => URI::regexp(%w(http https))
  validates :original_url, :url => true,:presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/link_urls_controller.rb
class LinkUrlsController < ApplicationController
  def new
  	@url = LinkUrl.new
  	letter = [('a'..'z'),('A'..'Z')].map {|i| i.to_a}.flatten
  	@url.random_id = (0...8).map {letter[rand(letter.length)]}.join
  end

  def index
  	@url = LinkUrl.all
  end


 def create
    @url = LinkUrl.new(url_params)
    if @url.save
    	redirect_to link_urls_index_path
    else
    	render "new"
  end
end

 def url_lists
  	@url = LinkUrl.all
    render json: {status: 'SUCCESS', message: 'Loaded all urls', data: @url}, status: :ok  
  end
  def show
    url = LinkUrl.where(:random_id=>params[:id]).first
    if url
    	 redirect_to url.original_url
    else
    	render 'index'
  end
end

  def url_params
    params.require(:link_url).permit(:original_url, :random_id)
  end
  
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/link_urls_helper.rb
module LinkUrlsHelper
end

app/views/layouts/application.html.erb
  
<!DOCTYPE html>
<html>
  <head>
    <title>URL</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "URL Shortener", '#', id: "logo" %>
        <nav>
          
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/link_urls/index.html.erb
<div class="card new_link_url">
  <div class="card-body">
  	<table>
  		<thead>
  			<tr>
  				<th>Short Url</th>
  				<th></th>
  				<th>Original Url</th>
  			</tr>
  		</thead>
  	<tbody>
<%@url.each do |url| %>
<tr>
<td>
	<%= link_to url.random_id, link_urls_show_path(:id => url.random_id)%></td> <td>=></td><td><%= url.original_url%></td>

</tr>
<%end%>
</tbody>
</table>
  </div>
</div>

<%= link_to "New URL",link_urls_new_path%>

app/views/link_urls/new.html.erb
<div class="new_link_url">
	<div class="error">
<% @url.errors.each do | attr,msg |%>
<%= msg%> on <%= attr %>
<%end%>
</div>
<%= form_for @url,:url => link_urls_create_url do | f |%>

<p>
	<%= f.label :original_url %> : <%= f.text_field :original_url%>
</p>
<%= f.hidden_field :random_id,:value => @url.random_id%>
<%= f.submit "Shorten Url "%>
<%end%>
</div>
<%= link_to "Home",link_urls_index_path%>